use_frameworks!

platform :ios, '10.0'

target 'FSOCNetworking_Example' do
  pod 'FSOCNetworking', :path => '../'
  pod 'FSOCUtils/SafeUtils'

  target 'FSOCNetworking_Tests' do
    inherit! :search_paths

    
  end
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end
